controller_list:
  - name: ''
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [
            arm_left_joint_1_s,
            arm_left_joint_2_l,
            arm_left_joint_3_e,
            arm_left_joint_4_u,
            arm_left_joint_5_r,
            arm_left_joint_6_b,
            arm_left_joint_7_t,
            arm_right_joint_1_s,
            arm_right_joint_2_l,
            arm_right_joint_3_e,
            arm_right_joint_4_u,
            arm_right_joint_5_r,
            arm_right_joint_6_b,
            arm_right_joint_7_t,
            torso_joint_b1]
  - name: sda20d/sda20d_R1_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_left_joint_1_s,
            arm_left_joint_2_l,
            arm_left_joint_3_e,
            arm_left_joint_4_u,
            arm_left_joint_5_r,
            arm_left_joint_6_b,
            arm_left_joint_7_t]
  - name: sda20d/sda20d_B1_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [torso_joint_b1]
  - name: sda20d/sda20d_R2_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [arm_right_joint_1_s,
            arm_right_joint_2_l,
            arm_right_joint_3_e,
            arm_right_joint_4_u,
            arm_right_joint_5_r,
            arm_right_joint_6_b,
            arm_right_joint_7_t]
  - name: left_gripper_controller
    joints: [left_gripper_finger_joint_a_1,
            left_gripper_finger_joint_a_2,
            left_gripper_finger_joint_a_3,
            left_gripper_finger_joint_a_4,
            left_gripper_finger_joint_b_1,
            left_gripper_finger_joint_b_2,
            left_gripper_finger_joint_b_3,
            left_gripper_finger_joint_b_4,
            left_gripper_finger_joint_c_1,
            left_gripper_finger_joint_c_2,
            left_gripper_finger_joint_c_3,
            left_gripper_finger_joint_c_4]
  - name: right_gripper_controller
    joints: [right_gripper_finger_joint_a_1,
            right_gripper_finger_joint_a_2,
            right_gripper_finger_joint_a_3,
            right_gripper_finger_joint_a_4,
            right_gripper_finger_joint_b_1,
            right_gripper_finger_joint_b_2,
            right_gripper_finger_joint_b_3,
            right_gripper_finger_joint_b_4,
            right_gripper_finger_joint_c_1,
            right_gripper_finger_joint_c_2,
            right_gripper_finger_joint_c_3,
            right_gripper_finger_joint_c_4]
